/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlydanhsachhoadon;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class QLKhachHang extends javax.swing.JFrame {
    DefaultTableModel dtmKhachHangs;
    DSKhachHang danhSachs;
    DefaultTableModel dtmUpdate;
    /**
     * Creates new form QLKhachHang
     */
    public QLKhachHang() {
        initComponents();
        myInits();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfrmUpdate = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbUpdate = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnLuu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcbLoaiKhachHang = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNgayRaHD = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDoiTuongKH = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDinhMuc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtQuocTich = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbKhachHangs = new javax.swing.JTable();

        jtbUpdate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã KH", "Tên KH", "Ngày ra HĐ", "Số lượng", "Đơn giá", "Đối tượng KH", "Định mức", "Quốc tịch", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtbUpdate);

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(btnLuu)
                .addContainerGap(333, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLuu)
                .addContainerGap())
        );

        javax.swing.GroupLayout jfrmUpdateLayout = new javax.swing.GroupLayout(jfrmUpdate.getContentPane());
        jfrmUpdate.getContentPane().setLayout(jfrmUpdateLayout);
        jfrmUpdateLayout.setHorizontalGroup(
            jfrmUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
            .addGroup(jfrmUpdateLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jfrmUpdateLayout.setVerticalGroup(
            jfrmUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfrmUpdateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Loại khách hàng :");

        jcbLoaiKhachHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KH Việt Nam", "KH nước ngoài" }));
        jcbLoaiKhachHang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbLoaiKhachHangItemStateChanged(evt);
            }
        });
        jcbLoaiKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbLoaiKhachHangActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã khách hàng :");

        jLabel3.setText("Họ tên :");

        jLabel4.setText("Số lượng :");

        jLabel5.setText("Ngày ra HĐ :");

        jLabel6.setText("Đơn giá :");

        txtDonGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonGiaActionPerformed(evt);
            }
        });

        jLabel7.setText("Đối tượng KH :");

        jLabel8.setText("Định mức :");

        jLabel9.setText("Quốc tịch :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jcbLoaiKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHoTen)
                            .addComponent(txtMaKH)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgayRaHD)
                            .addComponent(txtSoLuong))))
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(txtDoiTuongKH)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(20, 20, 20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDinhMuc, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(txtQuocTich))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtDoiTuongKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtDinhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtQuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jcbLoaiKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNgayRaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jButton1.setText("Hiển thị");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnXoa)
                .addGap(68, 68, 68)
                .addComponent(btnCapNhat)
                .addGap(48, 48, 48)
                .addComponent(btnTimKiem)
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addGap(48, 48, 48))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnCapNhat)
                    .addComponent(btnTimKiem)
                    .addComponent(jButton1))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jtbKhachHangs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã KH", "Họ tên", "Ngày ra HĐ", "Số lượng", "Đơn giá", "Đối tượng KH", "Định mức", "Quốc tịch", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbKhachHangs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbKhachHangsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbKhachHangs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 134, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbLoaiKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbLoaiKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbLoaiKhachHangActionPerformed

    private void txtDonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonGiaActionPerformed

    private void jcbLoaiKhachHangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbLoaiKhachHangItemStateChanged
        thietLapKhoa(jcbLoaiKhachHang.getSelectedIndex());
    }//GEN-LAST:event_jcbLoaiKhachHangItemStateChanged

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (jcbLoaiKhachHang.getSelectedIndex() == 0){
            danhSachs.themMoi(new KhachHangVietNam(txtDoiTuongKH.getText().trim(),
                    Double.parseDouble(txtDinhMuc.getText().trim()),
                    txtMaKH.getText().trim(),
                    txtHoTen.getText().trim(),
                    chuyenStringThanhDate(txtNgayRaHD.getText().trim()), 
                    Double.parseDouble(txtSoLuong.getText().trim()), 
                    Double.parseDouble(txtDonGia.getText().trim())));
                    napDuLieuVaoBang(dtmKhachHangs);
                    hienThiThongBao("Thêm thành công");
                    clearAllField();
        }else{
            danhSachs.themMoi(new KhachHangNuocNgoai(txtQuocTich.getText().trim(),
                   txtMaKH.getText().trim(),
                    txtHoTen.getText().trim(),
                    chuyenStringThanhDate(txtNgayRaHD.getText().trim()), 
                    Double.parseDouble(txtSoLuong.getText().trim()), 
                    Double.parseDouble(txtDonGia.getText().trim())));
                    napDuLieuVaoBang(dtmKhachHangs);
                    hienThiThongBao("Thêm thành công");
                    clearAllField();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        String ma = JOptionPane.showInputDialog("Nhập mã cần xóa : ");
        if (danhSachs.xoa(ma)){
            napDuLieuVaoBang(dtmKhachHangs);
            hienThiThongBao("Xóa thành công");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String ma = JOptionPane.showInputDialog("Nhập mã cần tìm : ");
        if (danhSachs.tim(ma)!= null){
            xoaDuLieuCu(dtmKhachHangs);
            themMotDong(1, danhSachs.tim(ma), dtmKhachHangs);
            hienThiThongBao("Tìm thành công");
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void jtbKhachHangsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbKhachHangsMouseClicked
        jtbKhachHangs.getSelectedRow();
    }//GEN-LAST:event_jtbKhachHangsMouseClicked

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        String ma = JOptionPane.showInputDialog("Nhập mã cần cập nhật : ");
        if (danhSachs.capNhat(ma)!= null){
            dtmUpdate = (DefaultTableModel) jtbUpdate.getModel();
            jtbUpdate.setModel(dtmUpdate);
            xoaDuLieuCu(dtmUpdate);
            themMotDong(1, danhSachs.capNhat(ma),dtmUpdate);
            jfrmUpdate.setVisible(true);
            jfrmUpdate.pack();
            jfrmUpdate.setLocationRelativeTo(null);
        }
        
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        String ma = dtmUpdate.getValueAt(0, 1).toString();
        if (danhSachs.capNhat(ma)instanceof KhachHangVietNam){
            danhSachs.khachHangs.set(danhSachs.khachHangs.indexOf(danhSachs.capNhat(ma)), new KhachHangVietNam(dtmUpdate.getValueAt(0, 6).toString(),
                    Double.parseDouble(dtmUpdate.getValueAt(0, 7).toString()), 
                    dtmUpdate.getValueAt(0, 1).toString(), 
                    dtmUpdate.getValueAt(0, 2).toString(), 
                    chuyenStringThanhDate(dtmUpdate.getValueAt(0, 3).toString()),
                    Double.parseDouble(dtmUpdate.getValueAt(0, 4).toString()), 
                    Double.parseDouble(dtmUpdate.getValueAt(0, 5).toString())));
                    napDuLieuVaoBang(dtmKhachHangs);
                    hienThiThongBao("Cập nhật thành công");
                    jfrmUpdate.setVisible(false);
           
        }else{
            danhSachs.khachHangs.set(danhSachs.khachHangs.indexOf(danhSachs.capNhat(ma)), new KhachHangNuocNgoai(dtmUpdate.getValueAt(0, 8).toString(),
                    dtmUpdate.getValueAt(0, 1).toString(), 
                    dtmUpdate.getValueAt(0, 2).toString(), 
                    chuyenStringThanhDate(dtmUpdate.getValueAt(0, 3).toString()),
                    Double.parseDouble(dtmUpdate.getValueAt(0, 4).toString()), 
                    Double.parseDouble(dtmUpdate.getValueAt(0, 5).toString())));
                    napDuLieuVaoBang(dtmKhachHangs);
                    hienThiThongBao("Cập nhật thành công");
                    jfrmUpdate.setVisible(false);
        }
        
    }//GEN-LAST:event_btnLuuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        napDuLieuVaoBang(dtmKhachHangs);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcbLoaiKhachHang;
    private javax.swing.JFrame jfrmUpdate;
    private javax.swing.JTable jtbKhachHangs;
    private javax.swing.JTable jtbUpdate;
    private javax.swing.JTextField txtDinhMuc;
    private javax.swing.JTextField txtDoiTuongKH;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtNgayRaHD;
    private javax.swing.JTextField txtQuocTich;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables

    private void myInits() {
        setTitle("Quan ly khach hang");
        setLocationRelativeTo(null);
        
        dtmKhachHangs = (DefaultTableModel) jtbKhachHangs.getModel();
        jtbKhachHangs.setModel(dtmKhachHangs);
        
        danhSachs = new DSKhachHang();
        thietLapKhoa(0);
    }
    private Date chuyenStringThanhDate(String date){
        try {
            return new SimpleDateFormat("dd/MM/yyyy").parse(date);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }
    private String chuyenDateThanhString(Date date){
        return new SimpleDateFormat("dd/MM/yyyy").format(date);
    }
    private void thietLapKhoa(int loaiKhachHang) {
       boolean OK = true;
       if (loaiKhachHang == 0){
           OK = false;
       }
       txtDoiTuongKH.setEnabled(!OK);
       txtDinhMuc.setEnabled(!OK);
       txtQuocTich.setEnabled(OK);
    }

    private void napDuLieuVaoBang(DefaultTableModel dtm) {
        xoaDuLieuCu(dtm);
        int stt = 0;
        for (KhachHang kh : danhSachs.khachHangs) {
            themMotDong(++stt, kh, dtm);
        }
    }

     private void xoaDuLieuCu(DefaultTableModel dtm) {
        while (dtm.getRowCount() > 0){
            dtm.removeRow(0);
        }
    }
    private void themMotDong(int stt, KhachHang kh, DefaultTableModel dtm) {
        if (kh instanceof KhachHangVietNam){
            dtm.addRow(new Object[]{
                "" + stt, kh.getMaKhachHang(), kh.getHoTen(), chuyenDateThanhString(kh.getNgayRaHoaDon()), kh.getSoLuong(), kh.getDonGia(), ((KhachHangVietNam) kh).getDoiTuongKhachHang(), ((KhachHangVietNam) kh).getDinhMuc(), null, ((KhachHangVietNam)kh).tinhThanhTien()
            });
        }else{
            dtm.addRow(new Object[]{
                "" + stt, kh.getMaKhachHang(), kh.getHoTen(), chuyenDateThanhString(kh.getNgayRaHoaDon()), kh.getSoLuong(), kh.getDonGia(), null, null, ((KhachHangNuocNgoai)kh).getQuocTich(), ((KhachHangNuocNgoai)kh).tinhThanhTien()
            });
        }
    }   
    

    private void hienThiThongBao(String thongBao) {
        JOptionPane.showMessageDialog(null, thongBao);
    }

    private void clearAllField() {
        txtDinhMuc.setText("");
        txtDoiTuongKH.setText("");
        txtDonGia.setText("");
        txtHoTen.setText("");
        txtMaKH.setText("");
        txtNgayRaHD.setText("");
        txtQuocTich.setText("");
        txtSoLuong.setText("");
    }
    
    
}
