
import core.Bus;
import core.Car;
import core.DSCar;
import core.LuxuryCar;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Administrator
 */
public class CarManager extends javax.swing.JFrame {

    private DefaultTableModel dtm;
    private DefaultTableModel dtm2;
    private DSCar danhSach;

    /**
     * Creates new form CarManager
     */
    public CarManager() {
        initComponents();
        myInis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameUpdate = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbUpdate = new javax.swing.JTable();
        btnSaveUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbLoaiXe = new javax.swing.JComboBox<String>();
        jLabel2 = new javax.swing.JLabel();
        txtBienSo = new javax.swing.JTextField();
        txtNhaSanXuat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSoChoNgoi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNamSanXuat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtGiaGoc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTuyenDuong = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCuocVanChuyen = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtLePhiTTDB = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCar = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnHienThi = new javax.swing.JButton();
        btnLietke = new javax.swing.JButton();

        tbUpdate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bien so", "Nha San Xuat", "So Cho Ngoi", "Nam San Xuat", "Gia Goc", "Tuyen Duong", "Cuoc Van Chuyen", "Le Phi TTDB"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbUpdate);

        btnSaveUpdate.setText("Save Update");
        btnSaveUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrameUpdateLayout = new javax.swing.GroupLayout(jFrameUpdate.getContentPane());
        jFrameUpdate.getContentPane().setLayout(jFrameUpdateLayout);
        jFrameUpdateLayout.setHorizontalGroup(
            jFrameUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameUpdateLayout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(btnSaveUpdate)
                .addContainerGap(289, Short.MAX_VALUE))
            .addGroup(jFrameUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrameUpdateLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2)
                    .addContainerGap()))
        );
        jFrameUpdateLayout.setVerticalGroup(
            jFrameUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameUpdateLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(btnSaveUpdate)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jFrameUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrameUpdateLayout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 62, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Loai xe");

        cbLoaiXe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bus", "LuxuryCar" }));
        cbLoaiXe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLoaiXeItemStateChanged(evt);
            }
        });

        jLabel2.setText("Bien so");

        jLabel3.setText("Nha San Xuat");

        jLabel4.setText("So Cho Ngoi");

        jLabel5.setText("Nam San Xuat");

        jLabel6.setText("Gia Goc");

        jLabel7.setText("Bus");

        jLabel8.setText("LuxuryCar");

        jLabel9.setText("Tuyen Duong");

        jLabel10.setText("Cuoc Van Chuyen");

        jLabel11.setText("le Phi TTDB");

        tbCar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bien so", "Nha San Xuat", "So Cho Ngoi", "Nam San Xuat", "Gia Goc", "Tuyen Duong", "Cuoc Van Chuyen", "Le Phi TTDB"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbCar);

        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btUpdate.setText(" Cap Nhat");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tim kiem");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnHienThi.setText("Hien Thi");
        btnHienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiActionPerformed(evt);
            }
        });

        btnLietke.setText("Liet Ke Danh Sach");
        btnLietke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLietkeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(41, 41, 41)
                                .addComponent(txtBienSo, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNhaSanXuat)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185)
                        .addComponent(jLabel8)
                        .addGap(116, 116, 116))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtSoChoNgoi, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnThem)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGiaGoc, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNamSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btnXoa)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(btUpdate)
                                .addGap(48, 48, 48)
                                .addComponent(btnTimKiem)
                                .addGap(18, 18, 18)
                                .addComponent(btnLietke)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(btnHienThi)
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtTuyenDuong, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(50, 50, 50)
                                        .addComponent(txtLePhiTTDB, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCuocVanChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(45, 45, 45))))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBienSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtTuyenDuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtCuocVanChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNhaSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtLePhiTTDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSoChoNgoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNamSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGiaGoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btUpdate)
                    .addComponent(btnXoa)
                    .addComponent(btnThem)
                    .addComponent(btnTimKiem)
                    .addComponent(btnHienThi)
                    .addComponent(btnLietke))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (cbLoaiXe.getSelectedIndex() == 0) {
            danhSach.themMoi(new Bus(txtTuyenDuong.getText().trim(), txtBienSo.getText().trim(), txtNhaSanXuat.getText().trim(), Integer.parseInt(txtSoChoNgoi.getText().trim()), StringToDate(txtNamSanXuat.getText().trim()), Double.parseDouble(txtGiaGoc.getText().trim())));
            addDataToTable();
            clearTextField();
        } else {
            danhSach.themMoi(new LuxuryCar(Double.parseDouble(txtCuocVanChuyen.getText().trim()), Double.parseDouble(txtLePhiTTDB.getText().trim()), txtBienSo.getText().trim(), txtNhaSanXuat.getText().trim(), Integer.parseInt(txtSoChoNgoi.getText().trim()), StringToDate(txtNamSanXuat.getText().trim()), Double.parseDouble(txtGiaGoc.getText().trim())));
            addDataToTable();
            clearTextField();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void cbLoaiXeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLoaiXeItemStateChanged
        // TODO add your handling code here:
        thietLapKhoa(cbLoaiXe.getSelectedIndex());
    }//GEN-LAST:event_cbLoaiXeItemStateChanged

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog("Nhap bien so xe can xoa: ");
        if (danhSach.xoaXe(input)) {
            addDataToTable();
            JOptionPane.showMessageDialog(null, "Xoa thanh cong");
        } else {
            addDataToTable();
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnHienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiActionPerformed
        // TODO add your handling code here:
        addDataToTable();
    }//GEN-LAST:event_btnHienThiActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog("Nhap bien so xe can tim: ");
        if (danhSach.timKiem(input) != null) {
            clearOldDateTable(dtm);
            add1Row(danhSach.timKiem(input));
        } else {
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnLietkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLietkeActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog("Nhap gia tien chi dinh: ");
        double giaChiDinh = Double.parseDouble(input);
        if (danhSach.danhSachXeCoGiaBanNhoHonGiaNguoiDungChiDinh(giaChiDinh) != null) {
            clearOldDateTable(dtm);
            for (Car car : danhSach.danhSachXeCoGiaBanNhoHonGiaNguoiDungChiDinh(giaChiDinh)) {
                add1Row(car);
            }
        }
    }//GEN-LAST:event_btnLietkeActionPerformed

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog("Nhap bien so xe can cap nhat ");
        if (danhSach.timKiem(input) != null) {
            dtm2 = (DefaultTableModel) tbUpdate.getModel();
            tbUpdate.setModel(dtm2);
            addDataToTableUpdate(danhSach.timKiem(input));
            jFrameUpdate.setTitle("cap nhat xe");
            jFrameUpdate.setVisible(true);
            jFrameUpdate.setLocationRelativeTo(null);
            jFrameUpdate.pack();
        } else {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_btUpdateActionPerformed

    private void btnSaveUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveUpdateActionPerformed
        // TODO add your handling code here:
        boolean check;
        String bienSo = dtm2.getValueAt(0, 0).toString();

        if (danhSach.timKiem(bienSo) instanceof Bus) {
            danhSach.danhSachXe().set(danhSach.danhSachXe().indexOf(danhSach.timKiem(bienSo)), new Bus(
                    dtm2.getValueAt(0, 5).toString(),
                    dtm2.getValueAt(0, 0).toString(),
                    dtm2.getValueAt(0, 1).toString(),
                    Integer.parseInt(dtm2.getValueAt(0, 2).toString()),
                    StringToDate(dtm2.getValueAt(0, 3).toString()),
                    Double.parseDouble(dtm2.getValueAt(0, 4).toString())));
            clearOldDateTable(dtm2);
            check = true;
        } else {
            danhSach.danhSachXe().set(danhSach.danhSachXe().indexOf(danhSach.timKiem(bienSo)), new LuxuryCar(
                    Double.parseDouble(dtm2.getValueAt(0, 6).toString()),
                    Double.parseDouble(dtm2.getValueAt(0, 7).toString()),
                    dtm2.getValueAt(0, 0).toString(),
                    dtm2.getValueAt(0, 1).toString(),
                    Integer.parseInt(dtm2.getValueAt(0, 2).toString()),
                    StringToDate(dtm2.getValueAt(0, 3).toString()),
                    Double.parseDouble(dtm2.getValueAt(0, 4).toString())));
            clearOldDateTable(dtm2);
            check = true;
        }
        if (check) {
            addDataToTable();
            jFrameUpdate.setVisible(false);
        }
    }//GEN-LAST:event_btnSaveUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btUpdate;
    private javax.swing.JButton btnHienThi;
    private javax.swing.JButton btnLietke;
    private javax.swing.JButton btnSaveUpdate;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbLoaiXe;
    private javax.swing.JFrame jFrameUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbCar;
    private javax.swing.JTable tbUpdate;
    private javax.swing.JTextField txtBienSo;
    private javax.swing.JTextField txtCuocVanChuyen;
    private javax.swing.JTextField txtGiaGoc;
    private javax.swing.JTextField txtLePhiTTDB;
    private javax.swing.JTextField txtNamSanXuat;
    private javax.swing.JTextField txtNhaSanXuat;
    private javax.swing.JTextField txtSoChoNgoi;
    private javax.swing.JTextField txtTuyenDuong;
    // End of variables declaration//GEN-END:variables

    private void myInis() {
        setTitle("quan ly xe");
        dtm = (DefaultTableModel) tbCar.getModel();
        tbCar.setModel(dtm);
        danhSach = new DSCar();
        setVisible(true);
        setLocationRelativeTo(null);
        thietLapKhoa(0);
    }

    private void thietLapKhoa(int i) {
        boolean OK = false;
        if (i == 0) {
            OK = true;
        }
        txtTuyenDuong.setEnabled(OK);
        txtCuocVanChuyen.setEnabled(!OK);
        txtLePhiTTDB.setEnabled(!OK);
    }

    private Date StringToDate(String trim) {
        try {
            return new SimpleDateFormat("yyyy").parse(trim);
        } catch (ParseException e) {
            e.printStackTrace();
        }
        return null;
    }

    private void addDataToTable() {
        clearOldDateTable(dtm);
        for (Car car : danhSach.danhSachXe()) {
            add1Row(car);
        }
    }

    private void clearOldDateTable(DefaultTableModel dtm) {
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
    }

    private void add1Row(Car car) {
        try {
            dtm.addRow(new Object[]{car.getBienSo(), car.getNhaSX(), car.getSoChoNgoi(), DateToString(car.getNamSX()), car.getGiaGoc(), ((Bus) car).getTuyenDuong(), null, null});
        } catch (ClassCastException e) {
            dtm.addRow(new Object[]{car.getBienSo(), car.getNhaSX(), car.getSoChoNgoi(), DateToString(car.getNamSX()), car.getGiaGoc(), null, ((LuxuryCar) car).getCuocVanChuyen(), ((LuxuryCar) car).getLePhiTTDB()});
        }
    }

    private Object DateToString(Date namSX) {
        return new SimpleDateFormat("yyyy").format(namSX);
    }

    private void clearTextField() {
        txtBienSo.setText("");
        txtCuocVanChuyen.setText("");
        txtGiaGoc.setText("");
        txtLePhiTTDB.setText("");
        txtNamSanXuat.setText("");
        txtNhaSanXuat.setText("");
        txtSoChoNgoi.setText("");
        txtTuyenDuong.setText("");
        cbLoaiXe.requestFocus();
    }

    private void addDataToTableUpdate(Car car) {
        try {
            dtm2.addRow(new Object[]{car.getBienSo(), car.getNhaSX(), car.getSoChoNgoi(), DateToString(car.getNamSX()), car.getGiaGoc(), ((Bus) car).getTuyenDuong(), null, null});
        } catch (ClassCastException e) {
            dtm2.addRow(new Object[]{car.getBienSo(), car.getNhaSX(), car.getSoChoNgoi(), DateToString(car.getNamSX()), car.getGiaGoc(), null, ((LuxuryCar) car).getCuocVanChuyen(), ((LuxuryCar) car).getLePhiTTDB()});
        }
    }

}
