/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlgv;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
 
/**
 *
 * @author Sun
 */
public class GiaoDien extends javax.swing.JFrame {
     static  String S ;
    /**
     * Creates new form GiaoDien
     */
    private boolean gt;
    private DSGV danhsach;
    
    DefaultTableModel model;
    public GiaoDien() {
        initComponents();
        Myinits();
     model  = (DefaultTableModel) tbdanhsachs.getModel();
     tbdanhsachs.setModel(model);
     danhsach = new DSGV();
        Loai(0);
        EnabledXoa();
                JframeNhapma jfn = new JframeNhapma();
                  jfn.setVisible(true);
                   
                
                 System.out.println(S);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbg = new javax.swing.ButtonGroup();
        jFrame2 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        tfma2 = new javax.swing.JTextField();
        tften2 = new javax.swing.JTextField();
        rdnam2 = new javax.swing.JRadioButton();
        rdnu2 = new javax.swing.JRadioButton();
        tfngayvao2 = new javax.swing.JTextField();
        tfmahopdong2 = new javax.swing.JTextField();
        tfsogio2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbtrangthai = new javax.swing.JLabel();
        btok = new javax.swing.JButton();
        btcancel = new javax.swing.JButton();
        tfluonngcb2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        tfma = new javax.swing.JTextField();
        tfngayvao = new javax.swing.JTextField();
        tfmahopdong = new javax.swing.JTextField();
        cboloai = new javax.swing.JComboBox();
        rdnam = new javax.swing.JRadioButton();
        rdnu = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdanhsachs = new javax.swing.JTable();
        tften = new javax.swing.JTextField();
        tfsogio = new javax.swing.JTextField();
        tfluongcb = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        tbnxoa = new javax.swing.JButton();
        bttim = new javax.swing.JButton();
        tbupdate = new javax.swing.JButton();
        tbnthem = new javax.swing.JButton();
        Xclose = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Minisize = new javax.swing.JLabel();
        lberrorma = new javax.swing.JLabel();

        jFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame2.setTitle("Update");
        jFrame2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jFrame2.setSize(new java.awt.Dimension(656, 455));

        buttonGroup1.add(rdnam2);
        rdnam2.setText("Nam");

        buttonGroup1.add(rdnu2);
        rdnu2.setText("Nữ");

        tfmahopdong2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfmahopdong2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Mã GV");

        jLabel11.setText("Tên GV");

        jLabel12.setText("Số Giờ");

        jLabel13.setText("Lương CB");

        jLabel14.setText("Ngày Vào");

        jLabel15.setText("Phái");

        jLabel17.setText("State");

        btok.setText("OK");
        btok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btokActionPerformed(evt);
            }
        });

        btcancel.setText("Cancel");
        btcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelActionPerformed(evt);
            }
        });

        tfluonngcb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfluonngcb2ActionPerformed(evt);
            }
        });

        jLabel16.setText("Mã Hợp Đồng");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(30, 30, 30)
                                .addComponent(tfma2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbtrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdnu2)
                                            .addComponent(tften2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rdnam2))
                                        .addGap(133, 133, 133)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel16))))))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfmahopdong2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfngayvao2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfsogio2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfluonngcb2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btok, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btcancel)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfma2)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfsogio2))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(tften2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(rdnam2)
                                .addGap(18, 18, 18)
                                .addComponent(rdnu2)))
                        .addGap(223, 223, 223))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfngayvao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfluonngcb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfmahopdong2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btcancel)
                            .addComponent(btok))
                        .addGap(74, 74, 74))))
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Giảng Viên");
        setBackground(new java.awt.Color(132, 129, 112));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setForeground(new java.awt.Color(255, 153, 0));

        tfngayvao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfngayvaoActionPerformed(evt);
            }
        });

        tfmahopdong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfmahopdongActionPerformed(evt);
            }
        });

        cboloai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboloai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GVCoHuu", "GVThinhGiang" }));
        cboloai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboloaiItemStateChanged(evt);
            }
        });
        cboloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboloaiActionPerformed(evt);
            }
        });

        rdnam.setBackground(new java.awt.Color(44, 62, 80));
        tbg.add(rdnam);
        rdnam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdnam.setForeground(new java.awt.Color(255, 255, 255));
        rdnam.setText("Nam");
        rdnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdnamActionPerformed(evt);
            }
        });

        rdnu.setBackground(new java.awt.Color(44, 62, 80));
        tbg.add(rdnu);
        rdnu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdnu.setForeground(new java.awt.Color(255, 255, 255));
        rdnu.setText("Nữ");
        rdnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdnuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Ngày Vào");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Mã Giáng Viên");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Loại");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Tên Giáng Viên");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Số Giờ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Phái");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("Mã Hợp Đồng");

        tbdanhsachs.setBackground(new java.awt.Color(108, 122, 137));
        tbdanhsachs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbdanhsachs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Giáng Viên", "Tên Giảng Viên", "Phái", "Số Giờ", "Lương", "Phụ Cấp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbdanhsachs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdanhsachsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbdanhsachs);

        tften.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftenActionPerformed(evt);
            }
        });

        tfsogio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfsogioActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("Lương CB");

        jPanel6.setBackground(new java.awt.Color(132, 129, 112));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 51)));

        tbnxoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbnxoa.setText("Xóa");
        tbnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnxoaActionPerformed(evt);
            }
        });

        bttim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bttim.setText("Tìm ");
        bttim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttimActionPerformed(evt);
            }
        });

        tbupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbupdate.setText("Update");
        tbupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbupdateActionPerformed(evt);
            }
        });

        tbnthem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbnthem.setText("Thêm");
        tbnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnthemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbnthem)
                .addGap(37, 37, 37)
                .addComponent(tbnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(bttim, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(tbupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tbnxoa)
                .addComponent(bttim)
                .addComponent(tbupdate)
                .addComponent(tbnthem))
        );

        Xclose.setBackground(new java.awt.Color(248, 148, 6));
        Xclose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Xclose.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("X");
        jLabel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        Minisize.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        Minisize.setForeground(new java.awt.Color(255, 255, 255));
        Minisize.setText("–");
        Minisize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinisizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout XcloseLayout = new javax.swing.GroupLayout(Xclose);
        Xclose.setLayout(XcloseLayout);
        XcloseLayout.setHorizontalGroup(
            XcloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, XcloseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Minisize)
                .addGap(55, 55, 55)
                .addComponent(jLabel10)
                .addGap(24, 24, 24))
        );
        XcloseLayout.setVerticalGroup(
            XcloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(Minisize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lberrorma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lberrorma.setForeground(new java.awt.Color(255, 19, 28));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(rdnu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rdnam, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(118, 118, 118))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboloai, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfma)
                                    .addComponent(tften)
                                    .addComponent(tfsogio, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(lberrorma, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfmahopdong)
                            .addComponent(tfngayvao)
                            .addComponent(tfluongcb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(118, Short.MAX_VALUE))))
            .addComponent(Xclose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Xclose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboloai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(tfma, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lberrorma, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tften, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfluongcb, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfngayvao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfmahopdong, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfsogio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(rdnam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdnu))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfngayvaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfngayvaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfngayvaoActionPerformed
    
   
   private boolean  PrimaryKeyMa()
   {
    for(GiangVien temp : danhsach.LayDanhSach())
    {
       if(tfma.getText().equals(temp.getMa()))
       {
           return false;
           
       }
      
    }
    return true ;
   }
    private void tbnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnthemActionPerformed
        // TODO add your handling code here:
          
    if(PrimaryKeyMa()== true)
         
    {    
        if(cboloai.getSelectedIndex() == 0 ) 
        {
         
            try {
                danhsach.themGV( new GVCoHuu( ChuyenStringSangDate(tfngayvao.getText()) ,  Double.parseDouble(tfluongcb.getText()) , tfma.getText().trim(),tften.getText().trim(), Integer.parseInt(tfsogio.getText()), gt)    );
            } catch (ParseException ex) {
                Logger.getLogger(GiaoDien.class.getName()).log(Level.SEVERE, null, ex);
                }
    }                                       
      else  {
                 danhsach.themGV( new GVThinhGiang( tfmahopdong.getText().trim() , tfma.getText().trim(),tften.getText().trim() , Integer.parseInt(tfsogio.getText()), gt));
        }  
        lberrorma.setText(null);
        RemoveAllTable();
        napDulieu();
        Refresh();
        EnabledXoa();
    }else {
        tfma.setText(null);
        lberrorma.setText("Mã đã tồn tại !");
    }
    
    }//GEN-LAST:event_tbnthemActionPerformed
       public void Refresh ()
       { 
           
         tfmahopdong.setText(null);
         tfluongcb.setText(null);
         tfma.setText(null);
         tfngayvao.setText(null);
         tfsogio.setText(null);
         tften.setText(null);
                 
       
       
       
       }
    /**
     *
     * @param text
     * @return
     */
    public Date ChuyenStringSangDate(String  text ) throws ParseException 
     {
              
              SimpleDateFormat formatter1 = new SimpleDateFormat("dd/MM/yyyy");
              Date date1 = formatter1.parse(text);
         return date1;
     }
     
     
     
    private void rdnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdnamActionPerformed
        // TODO add your handling code here:
        if( rdnam.isSelected())
        {   
          gt= true;
        }
        
        
    }//GEN-LAST:event_rdnamActionPerformed

    private void tfmahopdongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfmahopdongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfmahopdongActionPerformed

    private void tftenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftenActionPerformed

    private void tfsogioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfsogioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfsogioActionPerformed

    private void bttimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttimActionPerformed
        // TODO add your handling code here:
    
//      if(model.getRowCount()>1)
//      {    
//        String maTim = JOptionPane.showInputDialog("Nhập mã cần tìm ");
//         int i = 0;
//               
//           
//         
//         
//      }else {
//         RemoveAllTable();
//         napDulieu();
//      }
        
    }//GEN-LAST:event_bttimActionPerformed

    private void cboloaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboloaiItemStateChanged
        // TODO add your handling code here:
        Loai(cboloai.getSelectedIndex());
    }//GEN-LAST:event_cboloaiItemStateChanged

    private void rdnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdnuActionPerformed
        // TODO add your handling code here:
        if( rdnu.isSelected())
        {   
            gt = false;
        }
    }//GEN-LAST:event_rdnuActionPerformed

    private void tbnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnxoaActionPerformed
        // TODO add your handling code here:
          
           
           int index = tbdanhsachs.getSelectedRow();
             
             if(index >0)
               {
                    danhsach.xoaGV( model.getValueAt(index, 1).toString());
                    model.removeRow(index);
                  
               }else {
                      String magv = null ;
                  
              
                 if(magv.length() > 0 )
                {   
                  
                   for(int i = 0 ; i < model.getRowCount();i++)
                   {
                     if(magv.equals(model.getValueAt(i, 1).toString()))
                     {
                        
                        model.removeRow(i);
                        danhsach.xoaGV(magv);
                      
                     }
                    
                   }
                }
                 tbdanhsachs.setModel(model);
             }
           
        EnabledXoa();
    }//GEN-LAST:event_tbnxoaActionPerformed

    private void cboloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboloaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboloaiActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
          dispose();
        
    }//GEN-LAST:event_jLabel10MouseClicked

    private void MinisizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinisizeMouseClicked
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinisizeMouseClicked

    private void tbdanhsachsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdanhsachsMouseClicked
        // TODO add your handling code here:
   
        if( evt.getClickCount() == 2)
        {
           LayDuLieuTrongMang();
        }
        
    }//GEN-LAST:event_tbdanhsachsMouseClicked

    private void frame2 ()
    {
          
          jFrame2.setVisible(true);
          jFrame2.setLocationRelativeTo(this);
    
    }
    private void tbupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbupdateActionPerformed
        // TODO add your handling code here:
          LayDuLieuTrongMang();
          frame2();
         
        
    }//GEN-LAST:event_tbupdateActionPerformed

    private void btcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelActionPerformed
        // TODO add your handling code here:
        jFrame2.dispose();
    }//GEN-LAST:event_btcancelActionPerformed
    private String ChuyenDateSangString(Date date)
    {
      SimpleDateFormat  f = new SimpleDateFormat("dd/MM/YYY");
      String ngayvao = f .format(date);
      
        return ngayvao;
      
       
    }
    private void state (GiangVien temp)
    {   boolean ok = true ;
      if(temp instanceof GVCoHuu)
      {       
             ok =false;
      }
              tfngayvao2.setEnabled(!ok);
              tfluonngcb2.setEnabled(!ok);
              tfmahopdong2.setEnabled(ok);
    }
    private void refresh2()
    {
      tfluonngcb2.setText(null);
      tfma2.setText(null);
      tfmahopdong2.setText(null);
      tfngayvao2.setText(null);
      tfsogio2.setText(null);
      tften2.setText(null);
              
    
    }
    private void LayDuLieuTrongMang()
    {  
          refresh2();
          int index = tbdanhsachs.getSelectedRow();
                
          if(index >-1)
               {
          GiangVien temp = danhsach.LayDanhSach().get(index);
           if(temp instanceof GVCoHuu)
            {   
                state(temp);
                tfma2.setText(temp.getMa());
                tften2.setText(temp.getHoTen());
                tfsogio2.setText(String.valueOf(temp.getSoGio()) );
                tfluonngcb2.setText(String.valueOf( ((GVCoHuu)temp).getLuongCB()   ));
                tfngayvao2.setText(ChuyenDateSangString(((GVCoHuu)temp).getNgayVao()   ));
                lbtrangthai.setText("GVCoHuu");
                
              boolean phai = temp.isPhai();
              if(phai)
              {
                rdnam2.setSelected(true);
              }else {
                 rdnu2.setSelected(true);
              }
             
            }  else 
           {
                state(temp);
                tfma2.setText(temp.getMa());
                tften2.setText(temp.getHoTen());
                tfsogio2.setText(String.valueOf(temp.getSoGio()) );
                tfmahopdong2.setText(((GVThinhGiang)temp).getMaHopDong());
                lbtrangthai.setText("GVCoHuu");
              boolean phai = temp.isPhai();
              if(phai)
              {
                rdnam2.setSelected(true);
              }else {
                 rdnu2.setSelected(true);
              }
            
           
           
           }
                   
           
           
               }   
    }
     
   
    private void btokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btokActionPerformed
        // TODO add your handling code here:
        
        
        jFrame2.dispose();
    }//GEN-LAST:event_btokActionPerformed

    private void tfmahopdong2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfmahopdong2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfmahopdong2ActionPerformed

    private void tfluonngcb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfluonngcb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfluonngcb2ActionPerformed
      
    
      public void Loai (int ind )
      {  
         boolean khoa = true  ;
             if(0 == ind)
             {
               khoa = false;
             
             }
              tfmahopdong.setEnabled(khoa);
              tfluongcb.setEnabled( !khoa);
              tfngayvao.setEnabled(!khoa);
              Refresh();
         
      }
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GiaoDien().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Minisize;
    private javax.swing.JPanel Xclose;
    private javax.swing.JButton btcancel;
    private javax.swing.JButton btok;
    private javax.swing.JButton bttim;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cboloai;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lberrorma;
    private javax.swing.JLabel lbtrangthai;
    private javax.swing.JRadioButton rdnam;
    private javax.swing.JRadioButton rdnam2;
    private javax.swing.JRadioButton rdnu;
    private javax.swing.JRadioButton rdnu2;
    private javax.swing.JTable tbdanhsachs;
    private javax.swing.ButtonGroup tbg;
    private javax.swing.JButton tbnthem;
    private javax.swing.JButton tbnxoa;
    private javax.swing.JButton tbupdate;
    private javax.swing.JTextField tfluongcb;
    private javax.swing.JTextField tfluonngcb2;
    private javax.swing.JTextField tfma;
    private javax.swing.JTextField tfma2;
    private javax.swing.JTextField tfmahopdong;
    private javax.swing.JTextField tfmahopdong2;
    private javax.swing.JTextField tfngayvao;
    private javax.swing.JTextField tfngayvao2;
    private javax.swing.JTextField tfsogio;
    private javax.swing.JTextField tfsogio2;
    private javax.swing.JTextField tften;
    private javax.swing.JTextField tften2;
    // End of variables declaration//GEN-END:variables

    private void Myinits() {
         
       
      
        setLocationRelativeTo(this);
    }

    private void napDulieu() {
 
        
        for(GiangVien temp : danhsach.LayDanhSach()       )
        {
            
           if(temp instanceof  GVCoHuu)
           {
             model.addRow( new Object[]{ temp.getMa(),temp.getHoTen(),temp.isPhai(),temp.getSoGio(),temp.luong(),temp.phuCap() });
             
           }
           else if (temp instanceof  GVThinhGiang)
           {
             model.addRow( new Object[]{ temp.getMa(),temp.getHoTen(),temp.isPhai(),  null ,null,temp.phuCap() });
             
           }
           
     
            
        }  
       
            
    }
    
    private void RemoveAllTable() {
         model.setRowCount(0);
        }
      private void EnabledXoa()
      {   
           boolean ok = false ; 
           if(model.getRowCount() >0 )
           {
              tbnxoa.setEnabled(!ok);
           }
           else {
           tbnxoa.setEnabled(ok);
           }
      }
    }
  
