/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package checkboxdemo;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JCheckBox;

/**
 *
 * @author Sun
 */
public class Jcheckboxdemo2 extends javax.swing.JFrame {
     String Textshow = "";

    /**
     * Creates new form Jcheckboxdemo2
     */
    public Jcheckboxdemo2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlcheckbox = new javax.swing.JPanel();
        cbtoan = new javax.swing.JCheckBox();
        cbly = new javax.swing.JCheckBox();
        cbhoa = new javax.swing.JCheckBox();
        cbanhvan = new javax.swing.JCheckBox();
        cbnguvan = new javax.swing.JCheckBox();
        cbmithuat = new javax.swing.JCheckBox();
        cblichsu = new javax.swing.JCheckBox();
        cbdialy = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbshow = new javax.swing.JLabel();
        btshow = new javax.swing.JButton();
        btrm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Môn Yêu Thích");
        setBackground(new java.awt.Color(44, 62, 80));
        setLocation(new java.awt.Point(450, 450));

        pnlcheckbox.setBackground(new java.awt.Color(255, 255, 255));
        pnlcheckbox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cbtoan.setText("Toán");

        cbly.setText("Lý");

        cbhoa.setText("Hóa");

        cbanhvan.setText("Anh Văn");

        cbnguvan.setText("Ngữ Văn");

        cbmithuat.setText("Mĩ Thuật");

        cblichsu.setText("Lịch Sữ");

        cbdialy.setText("Địa Lý");

        javax.swing.GroupLayout pnlcheckboxLayout = new javax.swing.GroupLayout(pnlcheckbox);
        pnlcheckbox.setLayout(pnlcheckboxLayout);
        pnlcheckboxLayout.setHorizontalGroup(
            pnlcheckboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlcheckboxLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(pnlcheckboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbmithuat)
                    .addComponent(cbtoan))
                .addGap(97, 97, 97)
                .addGroup(pnlcheckboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cblichsu)
                    .addComponent(cbly))
                .addGap(74, 74, 74)
                .addGroup(pnlcheckboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbdialy)
                    .addComponent(cbhoa))
                .addGap(93, 93, 93)
                .addGroup(pnlcheckboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbnguvan)
                    .addComponent(cbanhvan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlcheckboxLayout.setVerticalGroup(
            pnlcheckboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlcheckboxLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlcheckboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbtoan)
                    .addComponent(cbly)
                    .addComponent(cbhoa)
                    .addComponent(cbanhvan))
                .addGap(18, 18, 18)
                .addGroup(pnlcheckboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbmithuat)
                    .addComponent(cblichsu)
                    .addComponent(cbdialy)
                    .addComponent(cbnguvan))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Môn Yêu Thích : ");

        lbshow.setText("  ");
        lbshow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btshow.setText("Hiển thị");
        btshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btshowActionPerformed(evt);
            }
        });

        btrm.setText("Xóa chọn");
        btrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btshow))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbshow, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btrm)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbshow, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btshow)
                    .addComponent(btrm))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlcheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(pnlcheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btshowActionPerformed
        // TODO add your handling code here:
            Textshow = new String();
        for(Component  i : pnlcheckbox.getComponents())
        {
        JCheckBox  ckb = (JCheckBox) i ;
          if(ckb instanceof JCheckBox)
          {
                if( ckb.isSelected() )
                {
                   Textshow += ckb.getText() + ",";
                
                }
          }
          
           int len;
          if( ( len = Textshow.length() ) > 0 )
          {
            lbshow.setText(Textshow.substring(0,len -1 ));
          
          }         
          
         
          
        }
        
        
    }//GEN-LAST:event_btshowActionPerformed

    private void btrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrmActionPerformed
        // TODO add your handling code here:
        
        
              
        for(Component  i : pnlcheckbox.getComponents())
        {
        JCheckBox ckb = (JCheckBox) i ;
          if(ckb instanceof JCheckBox)
          {
                if( ckb.isSelected())
                {
                    ckb.setSelected(false);
                    Textshow = "" ;
                  
                }
                
          }
          
          lbshow.setText(Textshow);
        
         
          
        }
        
    }//GEN-LAST:event_btrmActionPerformed

   
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jcheckboxdemo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jcheckboxdemo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jcheckboxdemo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jcheckboxdemo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jcheckboxdemo2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btrm;
    private javax.swing.JButton btshow;
    private javax.swing.JCheckBox cbanhvan;
    private javax.swing.JCheckBox cbdialy;
    private javax.swing.JCheckBox cbhoa;
    private javax.swing.JCheckBox cblichsu;
    private javax.swing.JCheckBox cbly;
    private javax.swing.JCheckBox cbmithuat;
    private javax.swing.JCheckBox cbnguvan;
    private javax.swing.JCheckBox cbtoan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbshow;
    private javax.swing.JPanel pnlcheckbox;
    // End of variables declaration//GEN-END:variables
}
