/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLiDanhSach;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author STARTSUPER
 */
public class KhachHangGUI extends javax.swing.JFrame {

    /**
     * Creates new form KhachHangGUI
     */
    DSKH ds=new DSKH();
    DefaultTableModel dm = new DefaultTableModel();
    public KhachHangGUI() {
        initComponents();
         String[] tenCot ={"Ma","Ho Ten","Ngay","SoLuong","Don Gia","DoiTuongKh","DinhMuc","Quoc Tich"};
         dm.setColumnIdentifiers(tenCot);
         this.jTable1.setModel(dm);
    }
    private void xuatTable(ArrayList<KhachHang> arr){
        for(int i=dm.getRowCount()-1;i>=0;i--)
            dm.removeRow(i);
        for(KhachHang v:arr)
            if(v instanceof KhachHangVietNam)
                dm.addRow(new Object[]{v.getMaKhachHang(),v.getHoTen(),v.getNgayHoaDon(),v.getSoLuong(),v.getDonGia(),((KhachHangVietNam)v).getDoiTuongKH(),((KhachHangVietNam)v).getDinhMuc()});
            else
                dm.addRow(new Object[]{v.getMaKhachHang(),v.getHoTen(),v.getNgayHoaDon(),v.getSoLuong(),v.getDonGia(),"","",((KhachHangNuocNgoai)v).getQuocTich()});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfma = new javax.swing.JTextField();
        tften = new javax.swing.JTextField();
        tfngay = new javax.swing.JTextField();
        tfsoluong = new javax.swing.JTextField();
        tfdongia = new javax.swing.JTextField();
        tfdoituongkh = new javax.swing.JTextField();
        tfdinhmuc = new javax.swing.JTextField();
        tfquoctich = new javax.swing.JTextField();
        rbKHVietNam = new javax.swing.JRadioButton();
        rbKHNuocNgoai = new javax.swing.JRadioButton();
        btthem = new javax.swing.JButton();
        btxoa = new javax.swing.JButton();
        bttim = new javax.swing.JButton();
        btcapnhap = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MaKH");

        jLabel2.setText("Ten");

        jLabel3.setText("Ngay");

        jLabel4.setText("SoLuong");

        jLabel5.setText("DonGia");

        jLabel6.setText("DoiTuongKH");

        jLabel7.setText("DinhMuc");

        jLabel8.setText("QuocTich");

        tften.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftenActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbKHVietNam);
        rbKHVietNam.setText("KhachHangVietNam");

        buttonGroup1.add(rbKHNuocNgoai);
        rbKHNuocNgoai.setText("KhachHangNuocNgoai");

        btthem.setText("Them");
        btthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthemActionPerformed(evt);
            }
        });

        btxoa.setText("xoa");
        btxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxoaActionPerformed(evt);
            }
        });

        bttim.setText("tim");
        bttim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttimActionPerformed(evt);
            }
        });

        btcapnhap.setText("CapNhap");
        btcapnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcapnhapActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(rbKHVietNam)
                .addGap(54, 54, 54)
                .addComponent(rbKHNuocNgoai))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btthem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btxoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bttim)
                        .addGap(18, 18, 18)
                        .addComponent(btcapnhap)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfdongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(172, 172, 172)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(53, 53, 53)
                                        .addComponent(tften, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(44, 44, 44)
                                        .addComponent(tfma, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfdinhmuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdoituongkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfquoctich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfdinhmuc, tfdoituongkh, tfdongia, tfma, tfngay, tfquoctich, tfsoluong, tften});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(tfma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdoituongkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(tften, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdinhmuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(tfngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfquoctich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfdongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbKHVietNam)
                    .addComponent(rbKHNuocNgoai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btthem)
                    .addComponent(btxoa)
                    .addComponent(bttim)
                    .addComponent(btcapnhap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tftenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftenActionPerformed

    private void btthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthemActionPerformed
        // TODO add your handling code here:
          String ma= this.tfma.getText();
            String ht= this.tften.getText();
            Date nkh = new Date();
            DateFormat df= new SimpleDateFormat("yyyy-m-d");
        try {
            nkh= df.parse(this.tfngay.getText());
        } catch (ParseException ex) {}
        int sl= Integer.parseInt(this.tfsoluong.getText());
            double dongia= Double.parseDouble(this.tfdongia.getText());
         KhachHang v;
         if(this.rbKHVietNam.isSelected()){
             String dtkh= this.tfdoituongkh.getText();
             double dm = Double.parseDouble(this.tfdinhmuc.getText());
             v= new KhachHangVietNam(dtkh, dm, dtkh, ht, nkh, sl, dongia);
         }
         else {
             String qt= this.tfquoctich.getText();
             v=new KhachHangNuocNgoai(qt, ma, ht, nkh, sl, dongia);
         }
         ds.them(v);
         this.xuatTable(ds.getM());
    }//GEN-LAST:event_btthemActionPerformed

    private void btcapnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcapnhapActionPerformed
        // TODO add your handling code here:
          String ma= this.tfma.getText();
            String ht= this.tften.getText();
            Date nkh = new Date();
            DateFormat df= new SimpleDateFormat("yyyy-m-d");
        try {
            nkh= df.parse(this.tfngay.getText());
        } catch (ParseException ex) {}
        int sl= Integer.parseInt(this.tfsoluong.getText());
            double dongia= Double.parseDouble(this.tfdongia.getText());
         KhachHang v;
         if(this.rbKHVietNam.isSelected()){
             String dtkh= this.tfdoituongkh.getText();
             double dm = Double.parseDouble(this.tfdinhmuc.getText());
             v= new KhachHangVietNam(dtkh, dm, dtkh, ht, nkh, sl, dongia);
         }
         else {
             String qt= this.tfquoctich.getText();
             v=new KhachHangNuocNgoai(qt, ma, ht, nkh, sl, dongia);
         }
         int i = this.jTable1.getSelectedRow();
         ds.capNhat(i, v);
         this.xuatTable(ds.getM());
    }//GEN-LAST:event_btcapnhapActionPerformed

    private void btxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxoaActionPerformed
        // TODO add your handling code here:
        ds.xoaMa(this.tfma.getText());
        this.xuatTable(ds.getM());
    }//GEN-LAST:event_btxoaActionPerformed

    private void bttimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttimActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,ds.timMa(this.tfma.getText()).toString());
    }//GEN-LAST:event_bttimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhachHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhachHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhachHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhachHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhachHangGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcapnhap;
    private javax.swing.JButton btthem;
    private javax.swing.JButton bttim;
    private javax.swing.JButton btxoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbKHNuocNgoai;
    private javax.swing.JRadioButton rbKHVietNam;
    private javax.swing.JTextField tfdinhmuc;
    private javax.swing.JTextField tfdoituongkh;
    private javax.swing.JTextField tfdongia;
    private javax.swing.JTextField tfma;
    private javax.swing.JTextField tfngay;
    private javax.swing.JTextField tfquoctich;
    private javax.swing.JTextField tfsoluong;
    private javax.swing.JTextField tften;
    // End of variables declaration//GEN-END:variables
}
