/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CORE.DANHSACHKHACHHANG;
import CORE.KHACHHANGNUOCNGOAI;
import CORE.KHACHHANGVIETNAM;
import CORE.KHACHHANG;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class QLKHACHHANG extends javax.swing.JFrame {

    protected DefaultTableModel dtm;
    protected DefaultTableModel dtmCapNhat;
    protected DANHSACHKHACHHANG danhSach;

    /**
     * Creates new form QLKHACHHANG
     */
    public QLKHACHHANG() {
        initComponents();
        myInis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbLoaiKhachHang = new javax.swing.JComboBox<String>();
        lbLoaiKhachHang = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMaKhachHang = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNgayHoaDon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbDoiTuongKH = new javax.swing.JComboBox<String>();
        jLabel9 = new javax.swing.JLabel();
        txtQuocTich = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtDinhMuc = new javax.swing.JTextField();
        btnHienThi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbKhachHang = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUpdate = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbLoaiKhachHang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "KHACHHANGVIETNAM", "KHACHHANGNUOCNGOAI" }));
        cbLoaiKhachHang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLoaiKhachHangItemStateChanged(evt);
            }
        });

        lbLoaiKhachHang.setText("Loai khach Hang");

        jLabel1.setText("Ma Khach Hang");

        jLabel2.setText("Ho Ten");

        jLabel3.setText("Ngay Ra Hoa Don");

        jLabel4.setText("So Luong");

        jLabel5.setText("Don Gia");

        jLabel6.setText("KHACH HANG VIET NAM");

        jLabel7.setText("KHACH HANG NUOC NGOAI");

        jLabel8.setText("Doi Tuong KH");

        cbDoiTuongKH.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SINH HOAT", "KINH DOANH", "SAN XUAT" }));
        cbDoiTuongKH.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDoiTuongKHItemStateChanged(evt);
            }
        });

        jLabel9.setText("Quoc Tich");

        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnCapNhat.setText("Cap Nhat");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnTim.setText("Tim");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel10.setText("Dinh Muc");

        btnHienThi.setText("Hien Thi");
        btnHienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiActionPerformed(evt);
            }
        });

        tbKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "maKH", "hoTen", "ngayRaHoaDon", "soLuong", "donGia", "doiTuongKH", "quocTich", "DinhMuc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbKhachHang);

        jLabel11.setText("Bang Cap Nhat Khach Hang");

        btnUpdate.setText(" Cap Nhat Thong Tin Khach Hang");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        tblUpdate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "maKH", "hoTen", "ngayRaHoaDon", "soLuong", "donGia", "doiTuongKhachHang", "quocTich", "dinhMuc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblUpdate);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(btnThem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbLoaiKhachHang)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(115, 115, 115)
                                        .addComponent(btnXoa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCapNhat)
                                        .addGap(94, 94, 94))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbLoaiKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNgayHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(104, 104, 104)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addGap(28, 28, 28)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(btnTim)
                                                            .addComponent(cbDoiTuongKH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(txtDinhMuc))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 422, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel9)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txtQuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                        .addComponent(btnHienThi))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(btnUpdate)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLoaiKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLoaiKhachHang)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cbDoiTuongKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtQuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNgayHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtDinhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String doiTuongKH = cbDoiTuongKH.getSelectedItem().toString();
        if (cbLoaiKhachHang.getSelectedIndex() == 0) {           
            danhSach.themMoi(new KHACHHANGVIETNAM(
                    doiTuongKH,
                    Double.parseDouble(txtDinhMuc.getText().trim()),
                    txtMaKhachHang.getText().trim(),
                    txtHoTen.getText().trim(),
                    chuyenChuoiThanhNgay(txtNgayHoaDon.getText().trim()),
                    Double.parseDouble(txtSoLuong.getText().trim()), 
                    Double.parseDouble(txtDonGia.getText().trim())));
            AddDataToTable();
            ClearAllTextField();
        } else {
            danhSach.themMoi(new KHACHHANGNUOCNGOAI(
                    txtQuocTich.getText().trim(), 
                    txtMaKhachHang.getText().trim(), 
                    txtHoTen.getText().trim(), 
                    chuyenChuoiThanhNgay(txtNgayHoaDon.getText().trim()), 
                    Double.parseDouble(txtSoLuong.getText().trim()), 
                    Double.parseDouble(txtDonGia.getText().trim())));
            AddDataToTable();
            ClearAllTextField();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void cbLoaiKhachHangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLoaiKhachHangItemStateChanged
        // TODO add your handling code here:
        thietLapKhoa(cbLoaiKhachHang.getSelectedIndex());
    }//GEN-LAST:event_cbLoaiKhachHangItemStateChanged

    private void cbDoiTuongKHItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDoiTuongKHItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDoiTuongKHItemStateChanged

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String maKH = JOptionPane.showInputDialog("Nhap ma Khach Hang muon xoa");
        if(danhSach.xoaKhachHangTheoMa(maKH)){
            AddDataToTable();
        }
                
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        String maKH = JOptionPane.showInputDialog("Nhap ma Khach Hang muon tim");
        for (KHACHHANG khachhang : danhSach.HienThi()) {
            if(khachhang.getMaKH().equalsIgnoreCase(maKH)){
                ClearOldDataTable(dtm);
                Add1Row(khachhang);
            }
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnHienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiActionPerformed
        // TODO add your handling code here:
//        for (KHACHHANG object : danhSach.HienThi()) {
//            ClearOldDataTable();
//            Add1Row(object);
//            ClearAllTextField();
//        }
    AddDataToTable();
    }//GEN-LAST:event_btnHienThiActionPerformed
    int index;
    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:      
        String maKH = JOptionPane.showInputDialog("Nhap ma Khach Hang muon cap nhat");
        KHACHHANG khachHang = danhSach.timKiemKH(maKH);        
        index = danhSach.HienThi().indexOf(khachHang);
        dtmCapNhat = (DefaultTableModel)tblUpdate.getModel();
        tblUpdate.setModel(dtmCapNhat); 
         try {
              ClearOldDataTable(dtmCapNhat);
            dtmCapNhat.addRow(new Object[]{
                khachHang.getMaKH(),
                khachHang.getHoTen(),
                khachHang.getNgayRaHoaDon(),
                khachHang.getSoLuong(),
                khachHang.getDonGia(),
                ((KHACHHANGVIETNAM) khachHang).getDoiTuongKH(),
                null,
                ((KHACHHANGVIETNAM) khachHang).getDinhMuc()});
        } catch(ClassCastException e) {
             ClearOldDataTable(dtmCapNhat);
            dtmCapNhat.addRow(new Object[]{
                khachHang.getMaKH(),
                khachHang.getHoTen(),
                khachHang.getNgayRaHoaDon(),
                khachHang.getSoLuong(),
                khachHang.getDonGia(),
                null,
                ((KHACHHANGNUOCNGOAI) khachHang).getQuocTich(),
                null});
        }
        
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        KHACHHANG kh = danhSach.HienThi().get(index);
        try {
            kh.setMaKH(dtmCapNhat.getValueAt(0, 0).toString());
            kh.setHoTen(dtmCapNhat.getValueAt(0, 1).toString());
            kh.setNgayRaHoaDon(chuyenChuoiThanhNgay(dtmCapNhat.getValueAt(0, 2).toString()));
            kh.setSoLuong(Double.parseDouble(dtmCapNhat.getValueAt(0, 3).toString()));
            kh.setDonGia(Double.parseDouble(dtmCapNhat.getValueAt(0, 4).toString()));
            ((KHACHHANGVIETNAM)kh).setDoiTuongKH(dtmCapNhat.getValueAt(0, 5).toString());
            ((KHACHHANGVIETNAM)kh).setDinhMuc(Double.parseDouble(dtmCapNhat.getValueAt(0, 7).toString()));
            JOptionPane.showMessageDialog(null, "Cap nhat thanh cong");
        } catch (ClassCastException e) {
            kh.setMaKH(dtmCapNhat.getValueAt(0, 0).toString());
            kh.setHoTen(dtmCapNhat.getValueAt(0, 1).toString());
            kh.setNgayRaHoaDon(chuyenChuoiThanhNgay(dtmCapNhat.getValueAt(0, 2).toString()));
            kh.setSoLuong(Double.parseDouble(dtmCapNhat.getValueAt(0, 3).toString()));
            kh.setDonGia(Double.parseDouble(dtmCapNhat.getValueAt(0, 4).toString()));
            ((KHACHHANGNUOCNGOAI)kh).setQuocTich(dtmCapNhat.getValueAt(0, 6).toString());
            JOptionPane.showMessageDialog(null, "Cap nhat thanh cong");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLKHACHHANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLKHACHHANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLKHACHHANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLKHACHHANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLKHACHHANG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnHienThi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbDoiTuongKH;
    private javax.swing.JComboBox<String> cbLoaiKhachHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbLoaiKhachHang;
    private javax.swing.JTable tbKhachHang;
    private javax.swing.JTable tblUpdate;
    private javax.swing.JTextField txtDinhMuc;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaKhachHang;
    private javax.swing.JTextField txtNgayHoaDon;
    private javax.swing.JTextField txtQuocTich;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables

    private void myInis() {
        setTitle("Swing");
        setLocationRelativeTo(null);
        dtm = (DefaultTableModel) tbKhachHang.getModel();
        tbKhachHang.setModel(dtm);
        danhSach = new DANHSACHKHACHHANG();
        thietLapKhoa(0);

    }

    private void thietLapKhoa(int i) {
        boolean OK = false;
        if (cbLoaiKhachHang.getSelectedIndex() == 0) {
            OK = true;
        }
        cbDoiTuongKH.setEnabled(OK);
        txtDinhMuc.setEnabled(OK);
        txtQuocTich.setEnabled(!OK);
    }

    private Date chuyenChuoiThanhNgay(String trim) {
        try {
            return new SimpleDateFormat("dd/MM/yyyy").parse(trim);
        } catch (ParseException e) {
            e.printStackTrace();
        }
        return null;
    }

    private void AddDataToTable() {
        ClearOldDataTable(dtm);
        for (KHACHHANG khachHang : danhSach.HienThi()) {
            Add1Row(khachHang);
        }
    }

    private void ClearOldDataTable(DefaultTableModel dtm) {
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
    }

    private void Add1Row(KHACHHANG khachHang) {
        try {
            dtm.addRow(new Object[]{
                khachHang.getMaKH(),
                khachHang.getHoTen(),
                khachHang.getNgayRaHoaDon(),
                khachHang.getSoLuong(),
                khachHang.getDonGia(),
                ((KHACHHANGVIETNAM) khachHang).getDoiTuongKH(),
                null,
                ((KHACHHANGVIETNAM) khachHang).getDinhMuc()});
        } catch(ClassCastException e) {
            dtm.addRow(new Object[]{
                khachHang.getMaKH(),
                khachHang.getHoTen(),
                khachHang.getNgayRaHoaDon(),
                khachHang.getSoLuong(),
                khachHang.getDonGia(),
                null,
                ((KHACHHANGNUOCNGOAI) khachHang).getQuocTich(),
                null});
        }
    }

    private void ClearAllTextField() {
        txtDinhMuc.setText("");
        txtDonGia.setText("");
        txtHoTen.setText("");
        txtMaKhachHang.setText("");
        txtNgayHoaDon.setText("");
        txtQuocTich.setText("");
        txtSoLuong.setText("");
        cbLoaiKhachHang.requestFocus();
    }

    private String chuyenNgayThanhChuoi(Date ngay) {
        return new SimpleDateFormat("dd/MM/yyyy").format(ngay);
    }

    
}
