
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class QLKhachHang extends javax.swing.JFrame {
    DefaultTableModel dtmKhachHangs, dtmCapNhat, dtmTong;
    DSKhachHang danhSachs;
    /**
     * Creates new form QLKhachHang
     */
    public QLKhachHang() {
        initComponents();
        myInits();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfrmCapNhat = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbCapNhat = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnLuu = new javax.swing.JButton();
        jfrmTong = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbTong = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcbLoaiKhachHang = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNgayRaHD = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDoiTuongKH = new javax.swing.JTextField();
        txtDinhMuc = new javax.swing.JTextField();
        txtQuocTich = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        btnHienThi = new javax.swing.JButton();
        btnTong = new javax.swing.JButton();
        btnChen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblKhachHangs = new javax.swing.JTable();

        jtbCapNhat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã KH", "Họ tên", "Ngày ra HĐ", "Số lượng", "Đơn giá", "Đối tượng KH", "Định mức", "Quốc tịch"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtbCapNhat);

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(496, 496, 496)
                .addComponent(btnLuu)
                .addContainerGap(564, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnLuu)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jfrmCapNhatLayout = new javax.swing.GroupLayout(jfrmCapNhat.getContentPane());
        jfrmCapNhat.getContentPane().setLayout(jfrmCapNhatLayout);
        jfrmCapNhatLayout.setHorizontalGroup(
            jfrmCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfrmCapNhatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jfrmCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jfrmCapNhatLayout.setVerticalGroup(
            jfrmCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfrmCapNhatLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jtbTong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Loại khách hàng", "Tổng số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtbTong);

        javax.swing.GroupLayout jfrmTongLayout = new javax.swing.GroupLayout(jfrmTong.getContentPane());
        jfrmTong.getContentPane().setLayout(jfrmTongLayout);
        jfrmTongLayout.setHorizontalGroup(
            jfrmTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfrmTongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jfrmTongLayout.setVerticalGroup(
            jfrmTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfrmTongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Loại khách hàng :");

        jcbLoaiKhachHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khách hàng Việt Nam", "Khách hàng nước ngoài" }));
        jcbLoaiKhachHang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbLoaiKhachHangItemStateChanged(evt);
            }
        });

        jLabel2.setText("Mã khách hàng :");

        jLabel3.setText("Họ tên :");

        txtHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenActionPerformed(evt);
            }
        });

        jLabel4.setText("Số lượng :");

        jLabel5.setText("Ngày ra HĐ :");

        jLabel6.setText("Đơn giá :");

        jLabel9.setText("Quốc tịch :");

        jLabel8.setText("Định mức :");

        jLabel7.setText("Đối tượng KH :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgayRaHD, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbLoaiKhachHang, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMa, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDonGia))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtDoiTuongKH))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDinhMuc)
                            .addComponent(txtQuocTich))))
                .addGap(91, 91, 91))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbLoaiKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNgayRaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtDoiTuongKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtDinhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtQuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnHienThi.setText("Hiển thị");
        btnHienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiActionPerformed(evt);
            }
        });

        btnTong.setText("Tổng");
        btnTong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTongActionPerformed(evt);
            }
        });

        btnChen.setText("Chèn");
        btnChen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnThem)
                .addGap(49, 49, 49)
                .addComponent(btnXoa)
                .addGap(74, 74, 74)
                .addComponent(btnTim)
                .addGap(49, 49, 49)
                .addComponent(btnCapNhat)
                .addGap(87, 87, 87)
                .addComponent(btnChen)
                .addGap(74, 74, 74)
                .addComponent(btnHienThi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(btnTong)
                .addGap(104, 104, 104))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTim)
                        .addComponent(btnCapNhat)
                        .addComponent(btnChen)
                        .addComponent(btnHienThi)
                        .addComponent(btnTong)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jtblKhachHangs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã KH", "Họ tên", "Ngày HĐ", "Số lượng", "Đơn giá", "Đối tượng KH", "Định mức", "Quốc tịch", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblKhachHangs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenActionPerformed

    private void jcbLoaiKhachHangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbLoaiKhachHangItemStateChanged
        thietLapKhoa(jcbLoaiKhachHang.getSelectedIndex());
    }//GEN-LAST:event_jcbLoaiKhachHangItemStateChanged

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (jcbLoaiKhachHang.getSelectedIndex() == 0){
            danhSachs.them(new KhachHangVietNam(txtDoiTuongKH.getText().trim(),
                    Double.parseDouble(txtDinhMuc.getText().trim()), 
                    txtMa.getText().trim(),
                    txtHoTen.getText().trim(), 
                    chuyenStringThanhDate(txtNgayRaHD.getText().trim()), 
                    Double.parseDouble(txtSoLuong.getText().trim()), 
                    Double.parseDouble(txtDonGia.getText().trim())));
                    napDuLieuVaoBang();
                    hienThiThongBao("Thêm thành công");
                    clearAllField();
        }else{
            danhSachs.them(new KhachHangNuocNgoai(txtQuocTich.getText().trim(), 
                    txtMa.getText().trim(),
                    txtHoTen.getText().trim(), 
                    chuyenStringThanhDate(txtNgayRaHD.getText().trim()), 
                    Double.parseDouble(txtSoLuong.getText().trim()), 
                    Double.parseDouble(txtDonGia.getText().trim())));
                    napDuLieuVaoBang();
                    hienThiThongBao("Thêm thành công");
                    clearAllField();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        String ma = JOptionPane.showInputDialog("Nhập mã cần xóa : ");
        if (danhSachs.xoa(ma)){
            napDuLieuVaoBang();
            hienThiThongBao("Xóa thành công");
        }else{
            hienThiThongBao("Xóa không thành công");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
         String ma = JOptionPane.showInputDialog("Nhập mã cần tìm : ");
        if (danhSachs.tim(ma)!= null){
            xoaDuLieuCu(dtmKhachHangs);
            themMotDong(1, danhSachs.tim(ma), dtmKhachHangs);
            hienThiThongBao("Tìm thành công");
        }else{
            hienThiThongBao("Tìm không thành công");
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnHienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiActionPerformed
        napDuLieuVaoBang();
    }//GEN-LAST:event_btnHienThiActionPerformed

    private void btnChenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChenActionPerformed
        String ma = JOptionPane.showInputDialog("Nhập số cần chèn : "); 
        if (jcbLoaiKhachHang.getSelectedIndex() == 0){
            danhSachs.chen(Integer.parseInt(ma) - 1,new KhachHangVietNam(txtDoiTuongKH.getText().trim(),
                    Double.parseDouble(txtDinhMuc.getText().trim()), 
                    txtMa.getText().trim(),
                    txtHoTen.getText().trim(), 
                    chuyenStringThanhDate(txtNgayRaHD.getText().trim()), 
                    Double.parseDouble(txtSoLuong.getText().trim()), 
                    Double.parseDouble(txtDonGia.getText().trim())));
                    napDuLieuVaoBang();
                    hienThiThongBao("Chèn thành công");
                    clearAllField();
        }else{
            danhSachs.chen(Integer.parseInt(ma) - 1,new KhachHangNuocNgoai(txtQuocTich.getText().trim(), 
                    txtMa.getText().trim(),
                    txtHoTen.getText().trim(), 
                    chuyenStringThanhDate(txtNgayRaHD.getText().trim()), 
                    Double.parseDouble(txtSoLuong.getText().trim()), 
                    Double.parseDouble(txtDonGia.getText().trim())));
                    napDuLieuVaoBang();
                    hienThiThongBao("Chèn thành công");
                    clearAllField();
        }
    }//GEN-LAST:event_btnChenActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        String ma = dtmCapNhat.getValueAt(0, 1).toString();
        if (danhSachs.tim(ma)instanceof KhachHangVietNam){
            danhSachs.capNhat(new KhachHangVietNam(dtmCapNhat.getValueAt(0, 6).toString(),
                    Double.parseDouble(dtmCapNhat.getValueAt(0, 7).toString()), 
                    dtmCapNhat.getValueAt(0, 1).toString(), 
                    dtmCapNhat.getValueAt(0, 2).toString(), 
                    chuyenStringThanhDate(dtmCapNhat.getValueAt(0, 3).toString()),
                    Double.parseDouble(dtmCapNhat.getValueAt(0, 4).toString()), 
                    Double.parseDouble(dtmCapNhat.getValueAt(0, 5).toString())));
                    napDuLieuVaoBang();
                    hienThiThongBao("Cập nhật thành công");
                    jfrmCapNhat.dispose();
        }else{
            danhSachs.capNhat(new KhachHangNuocNgoai(dtmCapNhat.getValueAt(0, 8).toString(),
                    dtmCapNhat.getValueAt(0, 1).toString(), 
                    dtmCapNhat.getValueAt(0, 2).toString(), 
                    chuyenStringThanhDate(dtmCapNhat.getValueAt(0, 3).toString()),
                    Double.parseDouble(dtmCapNhat.getValueAt(0, 4).toString()), 
                    Double.parseDouble(dtmCapNhat.getValueAt(0, 5).toString())));
                    napDuLieuVaoBang();
                    hienThiThongBao("Cập nhật thành công");
                    jfrmCapNhat.dispose();
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        String ma = JOptionPane.showInputDialog("Nhập mã cần cập nhật : ");
        if (danhSachs.tim(ma)!= null){
            xoaDuLieuCu(dtmCapNhat);
            themMotDong(1, danhSachs.tim(ma), dtmCapNhat);
            jfrmCapNhat.setVisible(true);
            jfrmCapNhat.pack();
            jfrmCapNhat.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnTongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTongActionPerformed
        jfrmTong.setVisible(true);
        jfrmTong.pack();
        jfrmTong.setLocationRelativeTo(null);
        xoaDuLieuCu(dtmTong);
        themMotDongTong(1, "Khách hàng Việt Nam");
        themMotDongTong(2, "Khách hàng nước ngoài");
    }//GEN-LAST:event_btnTongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnChen;
    private javax.swing.JButton btnHienThi;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnTong;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> jcbLoaiKhachHang;
    private javax.swing.JFrame jfrmCapNhat;
    private javax.swing.JFrame jfrmTong;
    private javax.swing.JTable jtbCapNhat;
    private javax.swing.JTable jtbTong;
    private javax.swing.JTable jtblKhachHangs;
    private javax.swing.JTextField txtDinhMuc;
    private javax.swing.JTextField txtDoiTuongKH;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtNgayRaHD;
    private javax.swing.JTextField txtQuocTich;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables

    private void myInits() {
        setTitle("Quản lý khách hàng ");
        
        setLocationRelativeTo(null);
        
        dtmKhachHangs = (DefaultTableModel) jtblKhachHangs.getModel();
        jtblKhachHangs.setModel(dtmKhachHangs);
        
        dtmCapNhat = (DefaultTableModel) jtbCapNhat.getModel();
        jtbCapNhat.setModel(dtmCapNhat);
        
        dtmTong = (DefaultTableModel) jtbTong.getModel();
        jtbTong.setModel(dtmTong);
                 
        danhSachs = new DSKhachHang();
        
        thietLapKhoa(0);
    }

    private void thietLapKhoa(int loaiKhachHang) {
        boolean OK = true;
        if (loaiKhachHang == 0){
            OK = false;
        }
        
        txtDoiTuongKH.setEnabled(!OK);
        txtDinhMuc.setEnabled(!OK);
        txtQuocTich.setEnabled(OK);
    }
    private Date chuyenStringThanhDate(String date){
        try {
            return new SimpleDateFormat("dd/MM/yyyy").parse(date);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }
    
    private String chuyenDateThanhString(Date date){
        return new SimpleDateFormat("dd/MM/yyyy").format(date);
    }

    private void napDuLieuVaoBang() {
        xoaDuLieuCu(dtmKhachHangs);
        int stt = 0;
        for (KhachHang kh : danhSachs.khachHangs) {
            themMotDong(++stt, kh, dtmKhachHangs);
        }
        
    }

    private void hienThiThongBao(String thongBao) {
        JOptionPane.showMessageDialog(null, thongBao);
    }

    private void clearAllField() {
        txtDinhMuc.setText("");
        txtDoiTuongKH.setText("");
        txtDonGia.setText("");
        txtHoTen.setText("");
        txtMa.setText("");
        txtNgayRaHD.setText("");
        txtQuocTich.setText("");
        txtSoLuong.setText("");
    }

    private void xoaDuLieuCu(DefaultTableModel dtm) {
        while (dtm.getRowCount() > 0){
            dtm.removeRow(0);
        }
    }

    private void themMotDong(int stt, KhachHang kh, DefaultTableModel dtm) {
        if (kh instanceof KhachHangVietNam){
            dtm.addRow( new Object[]{
                "" + stt, kh.getMaKhachHang(), kh.getHoTen(), chuyenDateThanhString(kh.getNgayRaHoaDon()), kh.getSoLuong(), kh.getDonGia(), ((KhachHangVietNam) kh).getDoiTuongKhachHang(), ((KhachHangVietNam) kh).getDinhMuc(), null, ((KhachHangVietNam) kh).tinhThanhTien()
            });
        }else{
            dtm.addRow( new Object[]{
                "" + stt, kh.getMaKhachHang(), kh.getHoTen(), chuyenDateThanhString(kh.getNgayRaHoaDon()), kh.getSoLuong(), kh.getDonGia(), null, null, ((KhachHangNuocNgoai) kh).getQuocTich(), ((KhachHangNuocNgoai) kh).tinhThanhTien()
            });
        }
    }
    
    private void themMotDongTong(int stt, String loaiKH){
        if (loaiKH.equalsIgnoreCase("Khách hàng Việt Nam")){
            dtmTong.addRow( new Object[]{
                "" + stt, "Khách hàng Việt Nam", danhSachs.tongSoLuong(loaiKH)
            });
        }
        if (loaiKH.equalsIgnoreCase("Khách hàng nước ngoài")){
            dtmTong.addRow( new Object[]{
                "" + stt, "Khách hàng nước ngoài", danhSachs.tongSoLuong(loaiKH)
            });
        }
    }
    
}
