/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import core.DSKhachHang;
import core.KhachHang;
import core.KhachHangNuocNgoai;
import core.KhachHangVietNam;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import sun.net.www.MimeTable;
import static sun.net.www.MimeTable.loadTable;

/**
 *
 * @author Administrator
 */
public class QLKhachHang extends javax.swing.JFrame {

    /**
     * Creates new form QLKhachHang
     */
    
    boolean loaiKhachHang = true;
    DefaultTableModel dtm;
    DSKhachHang khachHangs;
    public QLKhachHang() {
        initComponents();
        myInits();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfMaKh = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfTenKh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfNgayRaHD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfDoiTuongKH = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfDinhMuc = new javax.swing.JTextField();
        tfDonGia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfSoLUong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfQuocTich = new javax.swing.JTextField();
        jcb = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MaKh");

        jLabel2.setText("TenKh");

        jLabel3.setText("NgayRaHĐ");

        jLabel4.setText("Doi Tuong khach hang");

        jLabel5.setText("Dinh muc");

        jLabel6.setText("So Luong");

        jLabel7.setText("Don gia");

        jLabel8.setText("Quoc Tich");

        jcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KHVietNam", "KHNuocNgoai" }));
        jcb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbMouseClicked(evt);
            }
        });
        jcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbActionPerformed(evt);
            }
        });

        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhat.setText("Cap nhat");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnTim.setText("Tim");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnThem)
                .addGap(31, 31, 31)
                .addComponent(btnXoa)
                .addGap(26, 26, 26)
                .addComponent(btnCapNhat)
                .addGap(18, 18, 18)
                .addComponent(btnTim)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnCapNhat)
                    .addComponent(btnTim))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaKH", "TenKH", "NgayRaHD", "So luong", "Don gia", "Doi tuong KH", "Dinh muc", "Quoc tich"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(28, 28, 28))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfNgayRaHD, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(tfMaKh, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTenKh, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfDonGia, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(tfSoLUong))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(tfDinhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(tfDoiTuongKH, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(tfQuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfDoiTuongKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(tfQuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfDinhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfMaKh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(tfTenKh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(tfNgayRaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(tfSoLUong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(tfDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbMouseClicked
        // TODO add your handling code here:
        loaiKhachHang = jcb.getSelectedIndex() == 0;
    }//GEN-LAST:event_jcbMouseClicked

    @SuppressWarnings("empty-statement")
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (themKhachHang()) System.out.println("Them thanh cong");;
        
        reloadJTable();
        
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        khachHangs.xoaKhachHangTheoMaKh(tfMaKh.getText().trim());
        reloadJTable();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        removeAllElementJTable();
        KhachHang khachHang = khachHangs.timKhachHangTheoMa(tfMaKh.getText().trim());
        if (khachHang instanceof KhachHangVietNam){
                dtm.addRow(new Object[] {
                    khachHang.getMaKhString(),
                    khachHang.getHoTen(),
                    new SimpleDateFormat("dd/MM/yyyy").format(khachHang.getNgayRaHoaDon()),
                    khachHang.getSoLuong(),
                    khachHang.getDonGia(),
                    ((KhachHangVietNam) khachHang).getDoiTuongKhachHang(),
                    ((KhachHangVietNam) khachHang).getDinhMuc(),
                    "Viet Nam"
                });
            } else {
                dtm.addRow(new Object[] {
                    khachHang.getMaKhString(),
                    khachHang.getHoTen(),
                    new SimpleDateFormat("dd/MM/yyyy").format(khachHang.getNgayRaHoaDon()),
                    khachHang.getSoLuong(),
                    khachHang.getDonGia(),
                    null,
                    null,
                    ((KhachHangNuocNgoai) khachHang).getQuocTich()
                });
            }
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        for (KhachHang khachHang : khachHangs.getDanhSach()) {
            if (khachHang.getMaKhString().equalsIgnoreCase(tfMaKh.getText().trim())){
                if (loaiKhachHang){
                    khachHang = (new KhachHangVietNam(tfDoiTuongKH.getText().trim(), Double.parseDouble(tfDinhMuc.getText().trim()), tfMaKh.getText().trim(), tfTenKh.getText().trim(), stringToDate(tfNgayRaHD.getText().trim()), Double.parseDouble(tfSoLUong.getText().trim()), Double.parseDouble(tfDonGia.getText().trim())));
                } else {
                    khachHang = (new KhachHangNuocNgoai(tfQuocTich.getText().trim(), tfMaKh.getText().trim(), tfTenKh.getText().trim(), stringToDate(tfNgayRaHD.getText().trim()), Double.parseDouble(tfSoLUong.getText().trim()), Double.parseDouble(tfDonGia.getText().trim())));
                }
                khachHangs.capNhat(khachHang);
            }
        }
        reloadJTable();
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void jcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbActionPerformed
        // TODO add your handling code here:
        loaiKhachHang = jcb.getSelectedIndex() == 0;
        setEnablejTextField(loaiKhachHang);
        System.out.println(jcb.getSelectedIndex());
    }//GEN-LAST:event_jcbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcb;
    private javax.swing.JTextField tfDinhMuc;
    private javax.swing.JTextField tfDoiTuongKH;
    private javax.swing.JTextField tfDonGia;
    private javax.swing.JTextField tfMaKh;
    private javax.swing.JTextField tfNgayRaHD;
    private javax.swing.JTextField tfQuocTich;
    private javax.swing.JTextField tfSoLUong;
    private javax.swing.JTextField tfTenKh;
    // End of variables declaration//GEN-END:variables

    private void myInits() {
        setTitle("Quan ly khach hang");
        dtm = (DefaultTableModel) JTable.getModel();
        JTable.setModel(dtm);
        khachHangs = new DSKhachHang();
        setEnablejTextField(loaiKhachHang);
    }

    private Date stringToDate(String trim) {
        try {
            return new SimpleDateFormat("dd/MM/yyyy").parse(trim);
        } catch (ParseException ex) {
            Logger.getLogger(QLKhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    private boolean  themKhachHang() {
        if (loaiKhachHang){
            return khachHangs.themKhachHang(new KhachHangVietNam(tfDoiTuongKH.getText().trim(), Double.parseDouble(tfDinhMuc.getText().trim()), tfMaKh.getText().trim(), tfTenKh.getText().trim(), stringToDate(tfNgayRaHD.getText().trim()), Double.parseDouble(tfSoLUong.getText().trim()), Double.parseDouble(tfDonGia.getText().trim())));
        } else {
            return khachHangs.themKhachHang(new KhachHangNuocNgoai(tfQuocTich.getText().trim(), tfMaKh.getText().trim(), tfTenKh.getText().trim(), stringToDate(tfNgayRaHD.getText().trim()), Double.parseDouble(tfSoLUong.getText().trim()), Double.parseDouble(tfDonGia.getText().trim())));
        }
    }

    private void reloadJTable() {
        removeAllElementJTable();
        removeAllTextField();
        for (KhachHang khachHang : khachHangs.getDanhSach()) {
            if (khachHang instanceof KhachHangVietNam){
                dtm.addRow(new Object[] {
                    khachHang.getMaKhString(),
                    khachHang.getHoTen(),
                    new SimpleDateFormat("dd/MM/yyyy").format(khachHang.getNgayRaHoaDon()),
                    khachHang.getSoLuong(),
                    khachHang.getDonGia(),
                    ((KhachHangVietNam) khachHang).getDoiTuongKhachHang(),
                    ((KhachHangVietNam) khachHang).getDinhMuc(),
                    "Viet Nam"
                });
            } else {
                dtm.addRow(new Object[] {
                    khachHang.getMaKhString(),
                    khachHang.getHoTen(),
                    new SimpleDateFormat("dd/MM/yyyy").format(khachHang.getNgayRaHoaDon()),
                    khachHang.getSoLuong(),
                    khachHang.getDonGia(),
                    null,
                    null,
                    ((KhachHangNuocNgoai) khachHang).getQuocTich()
                });
            }
        }
    }

    private void removeAllElementJTable() {
        while(dtm.getRowCount() > 0)
            dtm.removeRow(0);
    }

    private void removeAllTextField() {
        tfMaKh.setText("");
        tfTenKh.setText("");
        tfSoLUong.setText("");
        tfNgayRaHD.setText("");
        tfDoiTuongKH.setText("");
        tfDinhMuc.setText("");
        tfDonGia.setText("");
        tfQuocTich.setText("");
    }

    private void setEnablejTextField(boolean bool) {
        tfQuocTich.setEnabled(!bool);
        tfDinhMuc.setEnabled(bool);
        tfDoiTuongKH.setEnabled(bool);
    }
}
