/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplicationqlkt;

import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gemini
 */
public class QuanLyGUI extends javax.swing.JFrame {
    private DefaultTableModel dtmthanhviens;
    private DanhSachThanhVien danhSach;
    private int chonxoa = -1;
  
    /**
     * Creates new form QuanLyGUI
     */
    public QuanLyGUI() {
        initComponents();
        myInits();
    }
    private void myInits(){
        setLocationRelativeTo(null);
        setTitle("Quản Lý Khen Thưởng");
        dtmthanhviens = (DefaultTableModel) jtabletv.getModel();
        jtabletv.setModel(dtmthanhviens);
        thietlapkhoa(0);
        danhSach = new DanhSachThanhVien();
       jbtnadd.setEnabled(false);
     
    }
    
    private void tatbatnutthem(){
        if(jcomboboxtheloai.getSelectedIndex() == 0){
           if(txthoten.getText().length()>0 && txtma.getText().length()>0 && txtnamhoc.getText().length()>0 && txtngaysinh.getText().length()>0 && txtsbb.getText().length()>0 && txtsdt.getText().length()>0){
              jbtnadd.setEnabled(true);
            }else{
             jbtnadd.setEnabled(false);
            }
        }else{
            if(txthoten.getText().length()>0 && txtma.getText().length()>0 && txtnamhoc.getText().length()>0 && txtngaysinh.getText().length()>0 && txtdtb.getText().length()>0 ){
                jbtnadd.setEnabled(true);
            }else{
                 jbtnadd.setEnabled(false);
            }
        }
    
    }
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabletv = new javax.swing.JTable();
        jPaneltxt = new javax.swing.JPanel();
        lbma = new javax.swing.JLabel();
        lbhoten = new javax.swing.JLabel();
        lbngaysinh = new javax.swing.JLabel();
        lbnamhoc = new javax.swing.JLabel();
        txtma = new javax.swing.JTextField();
        txthoten = new javax.swing.JTextField();
        txtngaysinh = new javax.swing.JTextField();
        txtnamhoc = new javax.swing.JTextField();
        lbdtb = new javax.swing.JLabel();
        txtdtb = new javax.swing.JTextField();
        lbsbb = new javax.swing.JLabel();
        txtsbb = new javax.swing.JTextField();
        lbsdt = new javax.swing.JLabel();
        txtsdt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jbtnadd = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonhienthitatca = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jcomboboxtheloai = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jtxttim = new javax.swing.JTextField();
        jbtntim = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldxoa = new javax.swing.JTextField();
        jbtnxxoama = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtabletv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã", "Họ tên", "Ngày sinh", "Năm học", "ĐTB", "SBB", "SDT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtabletv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabletvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtabletv);

        jPaneltxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbma.setText("Mã  ");

        lbhoten.setText("Họ tên");

        lbngaysinh.setText("Ngày Sinh");

        lbnamhoc.setText("Năm học");

        txtma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmaKeyTyped(evt);
            }
        });

        txthoten.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthotenKeyTyped(evt);
            }
        });

        txtngaysinh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtngaysinhKeyTyped(evt);
            }
        });

        txtnamhoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnamhocKeyTyped(evt);
            }
        });

        lbdtb.setText("ĐTB ");

        txtdtb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdtbKeyTyped(evt);
            }
        });

        lbsbb.setText("SBB ");

        txtsbb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsbbKeyTyped(evt);
            }
        });

        lbsdt.setText("SDT");

        txtsdt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsdtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPaneltxtLayout = new javax.swing.GroupLayout(jPaneltxt);
        jPaneltxt.setLayout(jPaneltxtLayout);
        jPaneltxtLayout.setHorizontalGroup(
            jPaneltxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneltxtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneltxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbdtb)
                    .addComponent(lbma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPaneltxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtma, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(txtdtb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPaneltxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneltxtLayout.createSequentialGroup()
                        .addComponent(lbhoten)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPaneltxtLayout.createSequentialGroup()
                        .addComponent(lbsbb)
                        .addGap(15, 15, 15)))
                .addGroup(jPaneltxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtsbb)
                    .addComponent(txthoten, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPaneltxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbngaysinh)
                    .addComponent(lbsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPaneltxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtngaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(txtsdt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbnamhoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnamhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPaneltxtLayout.setVerticalGroup(
            jPaneltxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneltxtLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPaneltxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneltxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbhoten, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPaneltxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbma, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneltxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneltxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbnamhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtnamhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPaneltxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPaneltxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbdtb)
                        .addComponent(txtdtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPaneltxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbsbb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtsbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbsdt)
                        .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jbtnadd.setText("Thêm");
        jbtnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaddActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        jButton1.setText("Giảng Viên Có Lương Cao Nhất");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonhienthitatca.setText("Hiển Thị Tất Cả");
        jButtonhienthitatca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonhienthitatcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jbtnadd)
                .addGap(26, 26, 26)
                .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addGap(26, 26, 26)
                .addComponent(jButtonhienthitatca)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnadd)
                    .addComponent(btnxoa)
                    .addComponent(jButton1)
                    .addComponent(jButtonhienthitatca))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Loai");

        jcomboboxtheloai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giảng Viên", "SInh Viên" }));
        jcomboboxtheloai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcomboboxtheloaiItemStateChanged(evt);
            }
        });
        jcomboboxtheloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboboxtheloaiActionPerformed(evt);
            }
        });

        jLabel1.setText("Nhập mã");

        jbtntim.setText("Tim");
        jbtntim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtntimActionPerformed(evt);
            }
        });

        jLabel2.setText("Nhập mã ");

        jbtnxxoama.setText("Xóa");
        jbtnxxoama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnxxoamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcomboboxtheloai, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnxxoama)
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxttim, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtntim, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcomboboxtheloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jtxttim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtntim)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldxoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnxxoama))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPaneltxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPaneltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    
    private void jbtnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaddActionPerformed
           boolean add = false;
        if(jcomboboxtheloai.getSelectedIndex() == 0){
           if(chuyenStringthanhDate(txtngaysinh.getText()) != null){
            add = danhSach.themThanhVien(
               new GiangVien(
                       Integer.parseInt(txtsbb.getText().trim())
                       ,Integer.parseInt(txtsdt.getText().trim())
                       ,txtma.getText().trim(),txthoten.getText().trim()
                       ,txtnamhoc.getText().trim()
                       ,chuyenStringthanhDate(txtngaysinh.getText().trim())));
           }
            
       }else{
            if(chuyenStringthanhDate(txtngaysinh.getText()) != null){
          add = danhSach.themThanhVien(new SinhVien(
                   Double.parseDouble(
                   txtdtb.getText().trim())
                   ,txtma.getText().trim()
                   ,txthoten.getText().trim()
                   ,txtnamhoc.getText().trim()
                   ,chuyenStringthanhDate(txtngaysinh.getText().trim())));
            }
        }
       napdulieuvaomodel();
      if(add){
          thongbao("Thêm thành công rồi nhé :) ");
          xoadulieujtextfield();
      }
       jbtnadd.setEnabled(false);
    }//GEN-LAST:event_jbtnaddActionPerformed

    private void jcomboboxtheloaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcomboboxtheloaiItemStateChanged
        thietlapkhoa(jcomboboxtheloai.getSelectedIndex());
         jbtnadd.setEnabled(false);
         xoadulieujtextfield();
    }//GEN-LAST:event_jcomboboxtheloaiItemStateChanged

    private void jcomboboxtheloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboboxtheloaiActionPerformed
        
    }//GEN-LAST:event_jcomboboxtheloaiActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
     String ma ="";
      if(chonxoa != -1){
          ma = dtmthanhviens.getValueAt(chonxoa,1).toString();
      }
      if(danhSach.xoaThanhVien(ma)){
          thongbao("Xóa thành công :> ");
          napdulieuvaomodel();
          chonxoa = -1;
      }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void jtabletvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabletvMouseClicked
        chonxoa = jtabletv.getSelectedRow();
    }//GEN-LAST:event_jtabletvMouseClicked

    private void txtmaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmaKeyTyped
      tatbatnutthem();
    }//GEN-LAST:event_txtmaKeyTyped

    private void txthotenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthotenKeyTyped
       tatbatnutthem(); 
    }//GEN-LAST:event_txthotenKeyTyped

    private void txtngaysinhKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtngaysinhKeyTyped
       tatbatnutthem();
    }//GEN-LAST:event_txtngaysinhKeyTyped

    private void txtdtbKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdtbKeyTyped
       tatbatnutthem();
    }//GEN-LAST:event_txtdtbKeyTyped

    private void txtsbbKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsbbKeyTyped
       tatbatnutthem();
    }//GEN-LAST:event_txtsbbKeyTyped

    private void txtsdtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsdtKeyTyped
       tatbatnutthem();
    }//GEN-LAST:event_txtsdtKeyTyped

    private void txtnamhocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamhocKeyTyped
       tatbatnutthem();
    }//GEN-LAST:event_txtnamhocKeyTyped

    private void jbtntimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtntimActionPerformed
        if(danhSach.timThanhVien(jtxttim.getText()) != null ){
            xoadulieucumodel();
            themmotdong(1,danhSach.timThanhVien(jtxttim.getText()));
            jtxttim.setText("");
        }
    }//GEN-LAST:event_jbtntimActionPerformed

    private void jButtonhienthitatcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonhienthitatcaActionPerformed
       xoadulieucumodel();
       napdulieuvaomodel();
    }//GEN-LAST:event_jButtonhienthitatcaActionPerformed

    private void jbtnxxoamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnxxoamaActionPerformed
       if(danhSach.xoaThanhVien(jTextFieldxoa.getText())){
           xoadulieucumodel();
           napdulieuvaomodel();
           jTextFieldxoa.setText("");
       }
    }//GEN-LAST:event_jbtnxxoamaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        xoadulieucumodel();
        for (ThanhVien tv : danhSach.giangVienThuongCaoNhat()) {
            themmotdong(1,tv);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyGUI().setVisible(true);
            }
        });
    }
    
    
    private Date chuyenStringthanhDate(String strdate){
        try {
            return new SimpleDateFormat("dd/MM/yyyy").parse(strdate);
                
        }catch(ParseException e) {
            thongbao("Nhap sai ngay sinh, nhap lai nhe :)) ");
            xoadulieujtextfield();
             return null;
        }
    }
    
    private String chuyenDatethanhString(Date date){
       return new SimpleDateFormat("dd/MM/yyyy").format(date);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnxoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonhienthitatca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPaneltxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextFieldxoa;
    private javax.swing.JButton jbtnadd;
    private javax.swing.JButton jbtntim;
    private javax.swing.JButton jbtnxxoama;
    private javax.swing.JComboBox<String> jcomboboxtheloai;
    private javax.swing.JTable jtabletv;
    private javax.swing.JTextField jtxttim;
    private javax.swing.JLabel lbdtb;
    private javax.swing.JLabel lbhoten;
    private javax.swing.JLabel lbma;
    private javax.swing.JLabel lbnamhoc;
    private javax.swing.JLabel lbngaysinh;
    private javax.swing.JLabel lbsbb;
    private javax.swing.JLabel lbsdt;
    private javax.swing.JTextField txtdtb;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtma;
    private javax.swing.JTextField txtnamhoc;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JTextField txtsbb;
    private javax.swing.JTextField txtsdt;
    // End of variables declaration//GEN-END:variables
    //0 la Giang Vien
    //1 la Sinh Vien
    private void thietlapkhoa(int item) {
        boolean isOK = true;
        if(item == 0){
            txtma.setEnabled(isOK);
            txthoten.setEnabled(isOK);
            txtngaysinh.setEnabled(isOK);
            txtnamhoc.setEnabled(isOK);
            txtdtb.setEnabled(!isOK);
            txtsbb.setEnabled(isOK);
            txtsdt.setEnabled(isOK);
        }else{
            txtma.setEnabled(isOK);
            txthoten.setEnabled(isOK);
            txtngaysinh.setEnabled(isOK);
            txtnamhoc.setEnabled(isOK);
            txtdtb.setEnabled(isOK);
            txtsbb.setEnabled(!isOK);
            txtsdt.setEnabled(!isOK); 
        }
        
    }

    private void napdulieuvaomodel() {
        xoadulieucumodel();
        int stt=0;
        for (ThanhVien tv : danhSach.thanhViens) {
            themmotdong(++stt,tv);
        }
    }

    private void themmotdong(int stt,ThanhVien tv) {
        try {
      dtmthanhviens.addRow(new Object[]{""+stt,tv.getMaThanhVien(),tv.getTen(),chuyenDatethanhString(tv.getNgaySinh()),tv.getNamHoc(),null,((GiangVien)tv).getSoBaiBao(),((GiangVien)tv).getSoDeTai()});
        } catch (ClassCastException e) {
      dtmthanhviens.addRow(new Object[]{""+stt,tv.getMaThanhVien(),tv.getTen(),chuyenDatethanhString(tv.getNgaySinh()),tv.getNamHoc(),((SinhVien)tv).getDiemTrungBinh(),null,null});      
        } catch (NullPointerException e){
            xoadulieujtextfield();
        }
    }

    private void xoadulieucumodel() {
        while(dtmthanhviens.getRowCount()>0){
            dtmthanhviens.removeRow(0);
        }
    }
    private void thongbao(String str){
        JOptionPane.showMessageDialog(rootPane, str);
    }

    private void xoadulieujtextfield() {
          
            txtma.setText("");
            txthoten.setText("");
            txtngaysinh.setText("");
            txtnamhoc.setText("");
            txtdtb.setText("");
            txtsbb.setText("");
            txtsdt.setText("");
    }
    
  
}


